# Generated by Django 3.2.23 on 2023-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(editable=False, max_length=254),
        ),
    ]
